inherit_mode:
  merge:
    - Exclude
Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Exclude:
    - 'app/services/**/*'
Security/Open:
  Exclude:
    - 'spec/services/justeat/get_dishes_justeat_service_spec.rb'
Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'app/views/**/*'
    - 'Guardfile'
  ExcludedMethods:
    - describe
    - it
    - resource
    - register
    - register_page
    - route_param
    - context
    - show
    - controller
