version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.6.0-rc1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
          AMQP_URL: amqp://localhost:5672
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
      - image: rabbitmq:3.5.4
        environment:
          AMQP_URL: amqp://localhost:5672
    working_directory: ~/circleci-demo-workflow
    services:
      - rabbitmq-server
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - rails-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: rails-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:create db:schema:load --trace

      - run:
          name: DB Seed
          command: RAILS_ENV=development bin/rails db:create db:migrate db:seed --trace

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Run rspec in parallel
          command: bundle exec rspec --profile
